### ISSUE TITLE
Major concerns

### ISSUE THREAD

**Issue by drchud** [13Clowns/_scrapers#4]
Let's clear the air here. Now why/what is the point of running this lambda scraper module thing when all i see is copy and paste from other peoples work?? It really make no since at all.
I loved that long speech u gave on a4k, about the scrapers. You were spot on. I wonder where those words came from?
Honestly i would like to see you back that up, prove you can fix them when broken. Just look in ur module, tons of broken ones u can fix.

**Comment by 13Clowns** [comment]
Where to begin?? So this is for fun we are learning and trying things out. Only a couple months into this and we have learned a lot. It's fun. Not taking any credit from anyone. 

Like yourself we have family, full time, jobs and other activities. This is a project for a little down time we have. To your concern of copy and paste, we us this for us personally so we do like to have updated scrapers while we are learning. We tried to make a scraper/fix and failed hard. Not giving up but reviewing logs and trial and errors. 

I hope this helps answer your question.

Thanks for the drop by.

**Comment by drchud** [comment]
Lol well i know making playlists, going thru xmls, changing things is fun. Personally i really enjoy writing and fixing scrapers. Its a fucking rush for me, maybe even like a high. This is what i enjoy and think its fun.
However i really don't like people just stealing scrapers, flooding the sites and when it breaks.....saying oh well.
Going that route like everyone else is really going to make you look like a real clown!
It doesn't matter if u took them from jewbmx and he said its fine. The thing is i know who origanlly wrote them, and honestly its not fair at all. 
I have no issue sharing scrapers, not one bit. But its a little fucked up if u can't even fix them when they break. Just means ur not contributing/pulling ur weight and all u want to do is steal. Its this kind of stuff that made other real devs just say fuck and quit. I really hope u can see my point. 
Think about it iac, i guess wanted to do this for some single scraper source even though we already have universal. Dumb idea in my opinion. But what is the point of just stealing them just to horde them in ur module till they are broken. Makes no since to me. Acting like freeloaders.

If you want to learn this stuff, thats fucking awesome :) We need more people like you. But please don't sacrifice my hard work or any real devs work just to flood ur addon with scrapers u didnt write in the first place. As much as i love fixing scrapers, I have so many down right now cause a lot of sites got fucked this holiday season. Merry fucking Christmas to me lol. Now my wrzcraft scraper has been acting up....cough, cough!

An great idea while u are learning is maybe running a private addon for a few people. Fixing stuff here and there, learning more python. This is how i started. I don't really see how this benifits anybody, even endusers. Whats different than joe blow fork down the street icon and fanart, maybe different playlists. People want quality links for their movies and tv shows. Just my thoughts.....

**Comment by 13Clowns** [comment]
I totally agree with you, but it took me a minute to get there. Your correct, fork change art and make some changes. This is/ was a rush at first cause your learning it. This is easy once you learn it. Then the really work comes in, the scrapers. This is what many do not realize. We just did after seeing how it can do some damage without knowing it. We spent a part of the weekend trying to figure out an issue and it appears it came from a scraper as much as we can tell. We want to be part of the cause and it will take some time. We are dedicated and will do what we can. 
To your point on doing a private addon, this is why we pulled Zanni. We have been fortunate enough to talk with some people that have been around the scene for a very long time and they have been very helpful in providing support, suggestions and help to newbie questions. We are starting Zanni or another addon privately, it will not be in the 13clowns repo and we will be doing exactly like you suggested. We came to this conclusion the other day when we were messing around with 13Clowns. We are making the addon now as we want, how we want to see it. A template if you will.
Just yesterday we put more than usual focus on the scrapers, not just changing urls but doing our best to see how the one we adjusted failed and caused errors, how debrid works with them among other things. 
Many things came from this as we thought of the lambda scraper set:
-over 300 scrapers! where to start?
-how many are useless because sites are down? lots of time to go through those!
-where did they all come from? are they hotlinking off each-other? That's bad!
-are named different but pulling from the same site? another possible concern!
-its seems endless but possible with lots of time. For 1 or 2 people is it worth it?
So yes, we get your point and are still at the drawing board. I want to assure you as it appears you may think this is I-A-C. I can assure you we are not, we came in when I-A-C got going, liked the concept and when they went silent we forked it. 
Hopefully this clears things up for you as I have seen how passionate you are when it comes to this by other conversations you have had. If you could help offer advise we would appreciate it, there are scrapers we like and use regularly. In your option do we need to find the original developer to use those in our private addon, which one day may get released publicly? What do your suggestion/standpoint as a starting point for a set of scrappers so that the addon can function and slowly be developed? These types of questions come up and we are thinking of them constantly. Heck we spent time on the folder structure and the need for it? Why not just drop all into one folder? Only reason we could think of was debugging. 
I hope this helps and look forward to hearing your suggestions. 

Thanks again,
Clownman,

**Comment by doko-desuka** [comment]
PS: drchud you shouldn't be writing code for GPL-licensed projects (anything related to Kodi) if you're gonna care so much that it's "stolen, copy-pasted" around.

**Comment by 13Clowns** [comment]
@doko-desuka thank for all you do.

Going to close. No more need from drama.

**Comment by drchud** [comment]
@doko-desuka What i was saying is that the idea of having a scraper module that everone can use and contribute, which is the whole reason dumbass iac started this right? Like i was saying we already have a scraper module called universal scrapers, and before for that was nan scrapers. 
Like i was saying its really pointless to try and do this again. 

And for ur info doko, its a fucking header get over it. They both worked on those scrapers weekly if not daily for almost a yr running placenta. The only real exdous fork running at the time. Shit was always being fixed. Can't say the same for everyone else cause the rest copy and pasted lol. Not one has learned to code since placenta's departure. That shows how saturated the kodi scene is with fake devs. 

Lol and now ur going to help 13clowns? What happened to to all that talk about SERIOUS legal trouble and not worth it cause u don't get paid? Ur a snitch, wouldn't trust u at all.

**Comment by drchud** [comment]
@doko-desuka Just in case u don't fucking believe me.....a lot of people use this type of header. Its meant to be funny u dumbass as u can see here https://en.wikipedia.org/wiki/Beerware  Its also apparent u dont have a sense of humor. Grow up dude!

**Comment by doko-desuka** [comment]
@drchud hahaha I love you bro.
I got angry at seeing one the few (original) scrapers that I wrote having that header written onto it, especially the first line of said header: "@tantrumdev wrote this file" -> No they fuckin didn't!

I don't mind helping with code if it's in exchange for something (anything) that I think is valuable. I also don't mind sharing if it's for something that I made for myself anyway. The code will exist by then, no point in hoarding it.  
If you don't value your time as much, then I hope you get around to that because it's pretty important.

As for the rest of your points, I think you're looking for bar fist-fights. I'm not, sorry. See you later.  
Sincerely,
"Snitch"
